name: 'github-actions-merger'
description: 'merge pull request with labels'
author: 'abema'
branding:
  icon: 'meh'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  merge_method:
    description: 'merge method'
    required: false
    default: 'merge'
  github_token:
    description: 'github token'
    required: true
  owner:
    description: 'owner'
    required: true
  repo:
    description: 'repository'
    required: true
  pr_number:
    description: 'pull request number'
    required: true
  comment:
    description: 'pull comment'
    required: true
